export default {
	["AFC Bournemouth"]: "/images/teams/bournmouth.png",
	["Leicester City FC"]: "/images/teams/leicester.png",
	["Manchester United FC"]: "/images/teams/manu-50.png",
	["Norwich City FC"]: "/images/teams/norwhich.png",
	["Chelsea FC"]: "/images/teams/chelsea-50.png",
	["Everton FC"]: "/images/teams/everton-50.png",
	["Tottenham Hotspur FC"]: "/images/teams/totenham.png",
	["Aston Villa FC"]: "/images/teams/villa-50.png",
	["Sunderland AFC"]: "/images/teams/sunderland.jpg",
	["Crystal Palace FC"]: "/images/teams/palace-50.png",
	["Swansea City FC"]: "/images/teams/swansea.png",
	["Watford FC"]: "/images/teams/watford.png",
	["Arsenal FC"]: "/images/teams/arsenal-50.png",
	["West Ham United FC"]: "/images/teams/westham.png",
	["Newcastle United FC"]: "/images/teams/newcastle.png",
	["Southampton FC"]: "/images/teams/south-50.png",
	["Stoke City FC"]: "/images/teams/stoke-city.png",
	["Liverpool FC"]: "/images/teams/liverpool.png",
	["West Bromwich Albion FC"]: "/images/teams/wba.png",
	["Manchester City FC"]: "/images/teams/manc-50.png",
};
